# Generated by Django 4.2.13 on 2024-06-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
